feat(full): Merge full-vnc and add tkinter

diff --git a/full/Dockerfile b/full/Dockerfile
--- a/full/Dockerfile
+++ b/full/Dockerfile
@@ -1,6 +1,39 @@
 # Dazzle do not supports ARG TRIGGER_REBUILD=2
 FROM gitpod/workspace-base:latest
 
+# Install Xvfb, JavaFX-helpers, Openbox window manager and emacs GTK
+RUN sudo install-packages xvfb x11vnc xterm openjfx libopenjfx-java openbox \
+            emacs-gtk
+
+# Overwrite this env variable to use a different window manager
+ENV WINDOW_MANAGER="openbox"
+
+USER root
+
+# Change the default number of virtual desktops from 4 to 1 (footgun)
+RUN sed -ri "s/<number>4<\/number>/<number>1<\/number>/" /etc/xdg/openbox/rc.xml
+
+# Install novnc
+RUN git clone --depth 1 https://github.com/novnc/noVNC.git /opt/novnc \
+    && git clone --depth 1 https://github.com/novnc/websockify /opt/novnc/utils/websockify
+COPY novnc-index.html /opt/novnc/index.html
+
+# Add VNC startup script
+COPY start-vnc-session.sh /usr/bin/
+RUN chmod +x /usr/bin/start-vnc-session.sh
+
+# This is a bit of a hack. At the moment we have no means of starting background
+# tasks from a Dockerfile. This workaround checks, on each bashrc eval, if the X
+# server is running on screen 0, and if not starts Xvfb, x11vnc and novnc.
+RUN echo "export DISPLAY=:0" >> ~/.bashrc
+RUN echo "[ ! -e /tmp/.X0-lock ] && (/usr/bin/start-vnc-session.sh &> /tmp/display-\${DISPLAY}.log)" >> ~/.bashrc
+
+### checks ###
+# no root-owned files in the home directory
+RUN notOwnedFile=$(find . -not "(" -user gitpod -and -group gitpod ")" -print -quit) \
+    && { [ -z "$notOwnedFile" ] \
+        || { echo "Error: not all files/dirs in $HOME are owned by 'gitpod' user & group"; exit 1; } }
+
 RUN echo "ws full starts"
 
 ### Install C/C++ compiler and associated tools ###
@@ -137,7 +170,7 @@ ENV PATH=$PATH:/home/gitpod/.nvm/versions/node/v${NODE_VERSION}/bin
 LABEL dazzle/layer=lang-python
 LABEL dazzle/test=tests/lang-python.yaml
 USER gitpod
-RUN sudo install-packages python3-pip
+RUN sudo install-packages python3-pip tk-dev
 
 ENV PATH=$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH
 RUN curl -fsSL https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash \
